### PR TITLE
Add indicator components

### PR DESCRIPTION
**Pull request by chihsuan**
https://github.com/Canner/canner/issues/70

Indicator amount & list

### CODE REVIEW

**Review by abz53378 — CHANGES_REQUESTED** [review]
@chihsuan, I think the `title` of `indicator` should be a property like data tag does `<string title="title" keyName="keyName" />`.  
So please move it out of uiParams, and get `title` from `props` directly, thanks.

**Comment by chihsuan** [comment]
@abz53378: I've moved `title` out of uiParmas for amount indicator. Thanks!

**Comment by abz53378** [comment]
Thanks, @chihsuan. And the list indicator should be changed, too.

**Comment by abz53378** [comment]
And please add these two components to the dependencies of `@canner/antd-components` which is the collection of all `@canner/antd-*` packages.

See here: https://github.com/Canner/antd-canner-components/blob/canary/packages/antd-components/package.json#L14

Thanks!

**Comment by chihsuan** [comment]
@abz53378: I've changed them. Thanks!

**Review by abz53378 — APPROVED** [review]

**Pull request merged**
